config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = seek
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to @flat, notice: 'Who knew heaven was a place on Earth?'
    else
      render :new
    end
  end

  def edit
    @flat = seek
  end

  def update
    @flat = seek
    if @flat.update(flat_params)
      redirect_to @flat, notice: 'Flat was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @flat = seek
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address)
  end

  def seek
    Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/flats/create.html.erb
<h1>Flats#create</h1>
<p>Find me in app/views/flats/create.html.erb</p>

app/views/flats/destroy.html.erb
<h1>Flats#destroy</h1>
<p>Find me in app/views/flats/destroy.html.erb</p>

app/views/flats/edit.html.erb
<h1>Flats#edit</h1>
<%= render 'form', flat: @flat %>

<%= link_to 'Back', flats_path %>
<p>Find me in app/views/flats/edit.html.erb</p>

app/views/flats/index.html.erb
<div class="container">
  <% @flats.each do |flat|%>
  <div class="card">
    <h3><%= flat.name %></h3>
    <p><%= flat.address%></p>
    <%= link_to "Check this ish...", flat_path(flat) %>
  </div>
<% end %>
</div>
<p>Find me in app/views/flats/index.html.erb</p>

app/views/flats/new.html.erb
<h1>Flats#new</h1>
<%= render 'form', flat: @flat %>

<%= link_to 'Back', flats_path %>
<p>Find me in app/views/flats/new.html.erb</p>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>

<p><%= @flat.address %></p>
<%= link_to "Edit", edit_flat_path(@flat)%>
<%= link_to "Eradicate me", flat_path(@flat), method: :delete%>
<%= link_to 'Back', flats_path %>

<p>Find me in app/views/flats/show.html.erb</p>

app/views/flats/update.html.erb
<h1>Flats#update</h1>
<p>Find me in app/views/flats/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Simple Airbnb</a>
      <a class="btn btn-outline-primary my-2 my-sm-0 ml-2" href="/flats/new">Add Flat</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="ml-auto flex">
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value="">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>